# Provide environment for Cypress E2E test, JS bundles building, and Docker images building
version: '3.7'

services:
  sysmaker-env:
    build:
      context: .
      dockerfile: .Dockerfile-env
      args:
        IMAGE_CYPRESS: cypress/base:${VER_CYPRESS}
    image: sysmaker/sysmaker-env:${IMAGE_TAG}
